networks:
  guesthub-network:
    driver: bridge
    ipam:
      driver: default

services:
  guesthub-nginx:
    container_name: guesthub-nginx
    image: nginx
    ports:
      - '${FORWARD_NGINX_PORT:-8080}:80'
    depends_on:
      - guesthub
    volumes:
      - ./src:/var/www
      - ./docker/nginx/app.conf:/etc/nginx/conf.d/default.conf
    networks:
      - guesthub-network

  guesthub:
    container_name: guesthub
    build:
      context: docker
      dockerfile: app.Dockerfile
    entrypoint: [ "/bin/sh", "/scripts/entrypoint.sh" ]
    command: php-fpm
    image: guesthub
    volumes:
      - ./src:/var/www
      - ./docker/scripts:/scripts:ro
      - ./docker/php/phpfpm.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./docker/php/local.ini:/usr/local/etc/php/php.ini
    networks:
      - guesthub-network

  guesthub-db:
    container_name: guesthub-db
    image: postgres:17
    environment:
      POSTGRES_USER: guesthub
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: guesthub
    ports:
      - '${FORWARD_DB_PORT:-5432}:5432'
    volumes:
      - guesthub-db-volume:/var/lib/postgresql/data
    networks:
      - guesthub-network

  guesthub-redis:
    container_name: guesthub-redis
    image: redis:alpine
    restart: unless-stopped
    ports:
      - '${FORWARD_REDIS_PORT:-6379}:6379'
    networks:
      - guesthub-network

volumes:
  guesthub-db-volume:
    name: guesthub-db-volume
